"""add qa_pairs

Revision ID: 7115e8d10243
Revises: 3a0b796e2274
Create Date: 2026-08-31 15:08:23.961380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7115e8d10243'
down_revision: Union[str, Sequence[str], None] = '3a0b796e2274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=120), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('reference_answer', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('eval_score', sa.Float(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('pending_answer', sa.Text(), nullable=True),
    sa.Column('pending_citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pending_model', sa.String(length=255), nullable=True),
    sa.Column('pending_finish_reason', sa.String(length=32), nullable=True),
    sa.Column('pending_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_qa_pairs_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_qa_pairs_project_id_projects')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_qa_pairs_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_pairs'))
    )
    op.create_index(op.f('ix_qa_pairs_created_by'), 'qa_pairs', ['created_by'], unique=False)
    op.create_index('ix_qa_pairs_project_id_created_at', 'qa_pairs', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_qa_pairs_status'), 'qa_pairs', ['status'], unique=False)
    op.create_index(
        "ix_qa_pairs_tags", "qa_pairs", ["tags"], unique=False, postgresql_using="gin"
    )
    op.drop_index(op.f('ix_projects_status_lease_expires_at'), table_name='projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_projects_status_lease_expires_at'), 'projects', ['status', 'lease_expires_at'], unique=False)
    op.drop_index('ix_qa_pairs_tags', table_name='qa_pairs', postgresql_using='gin')
    op.drop_index(op.f('ix_qa_pairs_status'), table_name='qa_pairs')
    op.drop_index('ix_qa_pairs_project_id_created_at', table_name='qa_pairs')
    op.drop_index(op.f('ix_qa_pairs_created_by'), table_name='qa_pairs')
    op.drop_table('qa_pairs')
    # ### end Alembic commands ###
