"""Add checklist_items.kind

Revision ID: 8c1f4e7ab203
Revises: 53c8d09a5af3
Create Date: 2026-09-04

Positive and negative test cases, as data rather than a naming convention. Existing
rows become `positive`: they were generated by a prompt that only ever proposed happy
paths, so that is what they are, and guessing from their wording would mislabel some.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8c1f4e7ab203"
down_revision: str | None = "53c8d09a5af3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

KIND_DEFAULT = "positive"


def upgrade() -> None:
    # `server_default` for the backfill, then dropped: the application supplies the
    # value on every insert, and leaving a default in the schema would let a row that
    # forgot it look deliberate.
    op.add_column(
        "checklist_items",
        sa.Column("kind", sa.String(length=16), nullable=False, server_default=KIND_DEFAULT),
    )
    op.alter_column("checklist_items", "kind", server_default=None)
    # The grid filters kind within a module, and the export filters it across a
    # project; both go through `project_id` first, so it extends that index rather
    # than adding a second one.
    op.create_index(
        "ix_checklist_items_project_id_kind",
        "checklist_items",
        ["project_id", "kind"],
    )


def downgrade() -> None:
    op.drop_index("ix_checklist_items_project_id_kind", table_name="checklist_items")
    op.drop_column("checklist_items", "kind")
